### PR TITLE
fix(storage): calculates withdrawable funds and disables the action when no funds

### LINKED ISSUE #470: Problems with Withdrawable and Available Funds
There is a problem with the values we are displaying for **Withdrawable** and **Available** funds for both Consumer and Provider. These are obtained from the Cache but they do not get updated unless there is transaction, so they become invalid and obsolete as time passes.

We need to get this values from the Contract, or ensure the Cache tracks offers/agreements and maintains an updated status in real time.

### PR DESCRIPTION
**Pull request by farinalvaro**
Closes #470 

Sometimes we are getting negative periods from the cache, https://github.com/rsksmart/rif-marketplace-cache/pull/384 would fix that

### CODE REVIEW

File: src/components/molecules/SelectRowButton.tsx [hunk 1]
```diff
@@ -5,6 +5,7 @@ export interface SelectRowButtonProps {
   className?: string
   id: string
   handleSelect: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void
+  disabled?: boolean
 }
```
Comment (jurajpiar) [inline src/components/molecules/SelectRowButton.tsx:9]: on hindside, the `SelectRowButtonProps` should probably just expose MUI `ButtonProps`. or perhaps it shouldn't be there at all.

**Review by jurajpiar — APPROVED** [review]

**Review by julianmrodri — APPROVED** [review]
LGTM
